# Python 3.8.18 이미지를 기반으로 함
FROM python:3.9.6

# 작업 디렉토리 설정
WORKDIR /app

# 현재 디렉토리의 내용을 컨테이너의 작업 디렉토리로 복사
COPY . /app

RUN pip install --upgrade pip
# 필요한 패키지가 명시된 requirements.txt를 사용하여 패키지 설치
RUN pip install --no-cache-dir -r requirements.txt

# Playwright가 필요로 하는 의존성 설치
RUN apt-get update && apt-get install -y \
  libnss3 \
  libnspr4 \
  libdbus-1-3 \
  libatk1.0-0 \
  libatk-bridge2.0-0 \
  libcups2 \
  libatspi2.0-0 \
  libxcomposite1 \
  libxdamage1 \
  libxfixes3 \
  libxrandr2 \
  libgbm1 \
  libdrm2 \
  libxkbcommon0 \
  libasound2 \
  && rm -rf /var/lib/apt/lists/*
RUN playwright install  

# MySQL 서비스의 호스트 이름과 포트를 지정
ENV MYSQL_HOST=my-mysql-db
ENV MYSQL_PORT=3307

# 컨테이너 실행 시 main.py 실행
# CMD ["python", "./main.py"]
